package FrontEnd;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import BackEnd.*;
//String name=JOptionPane.showInputDialog(null, "Plz enter your name “);
//JOptionPane.showMessageDialog(null, "Welcome "+ name +" to Java!“);


/**
 *
 * @author NOUR
 */
public class ProfileManagementPage extends javax.swing.JFrame {
    private BufferedImage coverImage;
    private BufferedImage profileImage;
    ProfileManagement profilemanager = new ProfileManagement();
    
    /**
     * Creates new form ProfileManagementPage
     */
    public ProfileManagementPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        coverPhotoJPanel = new javax.swing.JPanel();
        profilePhotoJPanel = new javax.swing.JPanel();
        viewCoverPhotoButton = new javax.swing.JButton();
        changeCoverPhotoButton = new javax.swing.JButton();
        viewProfilePhotoButton = new javax.swing.JButton();
        changeProfilePhotoButton = new javax.swing.JButton();
        bioJLabel = new javax.swing.JLabel();
        updatePasswordButton = new javax.swing.JButton();
        changeBioButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        coverPhotoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout coverPhotoJPanelLayout = new javax.swing.GroupLayout(coverPhotoJPanel);
        coverPhotoJPanel.setLayout(coverPhotoJPanelLayout);
        coverPhotoJPanelLayout.setHorizontalGroup(
            coverPhotoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        coverPhotoJPanelLayout.setVerticalGroup(
            coverPhotoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        profilePhotoJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout profilePhotoJPanelLayout = new javax.swing.GroupLayout(profilePhotoJPanel);
        profilePhotoJPanel.setLayout(profilePhotoJPanelLayout);
        profilePhotoJPanelLayout.setHorizontalGroup(
            profilePhotoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        profilePhotoJPanelLayout.setVerticalGroup(
            profilePhotoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        viewCoverPhotoButton.setText("View Cover Photo");
        viewCoverPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoverPhotoButtonActionPerformed(evt);
            }
        });

        changeCoverPhotoButton.setText("Change Cover Photo");
        changeCoverPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCoverPhotoButtonActionPerformed(evt);
            }
        });

        viewProfilePhotoButton.setText("View Profile Photo");
        viewProfilePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfilePhotoButtonActionPerformed(evt);
            }
        });

        changeProfilePhotoButton.setText("Change Profile Photo");
        changeProfilePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeProfilePhotoButtonActionPerformed(evt);
            }
        });

        bioJLabel.setText("Bio");

        updatePasswordButton.setText("Update Password");
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });

        changeBioButton.setText("Change Bio");
        changeBioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coverPhotoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewProfilePhotoButton)
                            .addComponent(changeProfilePhotoButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profilePhotoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewCoverPhotoButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(changeCoverPhotoButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bioJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(changeBioButton)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(updatePasswordButton)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(profilePhotoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coverPhotoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(viewProfilePhotoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeProfilePhotoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewCoverPhotoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeCoverPhotoButton)
                                .addGap(18, 18, 18)
                                .addComponent(bioJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))))
                .addComponent(updatePasswordButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeBioButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeBioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBioButtonActionPerformed
        // TODO add your handling code here:
        EditBioWindow editbiowindow = new EditBioWindow();
        editbiowindow.setVisible(true);
        
        String newBio = editbiowindow.getBioText();
        System.out.println(newBio);
        bioJLabel.setText(newBio); 
        profilemanager.updateBio(newBio);
    }//GEN-LAST:event_changeBioButtonActionPerformed

    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        // TODO add your handling code here:
        JPasswordField passwordField = new JPasswordField(20);//field with 20 characters available 
        int option = JOptionPane.showConfirmDialog(null, passwordField, 
        "Enter new password", JOptionPane.OK_CANCEL_OPTION);//prompt the user for a password
        
        if (option == JOptionPane.OK_OPTION) {
        char[] passwordChars = passwordField.getPassword();//get password entered by user
        String newPassword = new String(passwordChars);//char[] password to String      
        profilemanager.updatePassword(UserAccount.hashPassword(newPassword));//save it in profileManager
    }
    }//GEN-LAST:event_updatePasswordButtonActionPerformed

    private void changeCoverPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCoverPhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png"));
        //types of files that can be chosen from
        int result = fileChooser.showOpenDialog(this);//Show open file dialog  
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();//capture selected file
            try {
                coverImage = ImageIO.read(selectedFile);//read and capture image file   
                profilemanager.updateCoverPhoto(selectedFile.getAbsolutePath());
                coverPhotoJPanel.getGraphics().drawImage(coverImage, 0, 0, coverPhotoJPanel.getWidth(), coverPhotoJPanel.getHeight(), this);
                //display photo on cover photo JPanel
            } catch (IOException e) {
                e.printStackTrace(); //Handle file not found, etc..
            }}
    }//GEN-LAST:event_changeCoverPhotoButtonActionPerformed

    private void changeProfilePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeProfilePhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image files", "jpg", "png"));
        //types of files that can be chosen from
        int result = fileChooser.showOpenDialog(this);//show open file dialog 
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();//capture selected file
            try {
                profileImage = ImageIO.read(selectedFile);//read and capture image file 
                profilemanager.updateProfilePhoto(selectedFile.getAbsolutePath());
                profilePhotoJPanel.getGraphics().drawImage(profileImage, 0, 0, profilePhotoJPanel.getWidth(), profilePhotoJPanel.getHeight(), this);
                //display photo on profile photo JPanel
            } catch (IOException e) {
                e.printStackTrace();  // Handle file not found, etc..
            }
        }
    }//GEN-LAST:event_changeProfilePhotoButtonActionPerformed

    private void viewCoverPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoverPhotoButtonActionPerformed
        // TODO add your handling code here:
    if (coverImage != null) {       
        JFrame fullSizeFrame = new JFrame("Full Size Cover Photo");// New JFrame to display pic in Full size       
        fullSizeFrame.setSize(coverImage.getWidth(), coverImage.getHeight());// Set frame size = image size      
        JLabel imageLabel = new JLabel(new ImageIcon(coverImage));//JLabel to display the image        
        fullSizeFrame.add(imageLabel);// Add image label to frame
        fullSizeFrame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No cover photo available.");
    }
    }//GEN-LAST:event_viewCoverPhotoButtonActionPerformed

    private void viewProfilePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfilePhotoButtonActionPerformed
        // TODO add your handling code here:
 if (profileImage != null) {      
        JFrame fullSizeFrame = new JFrame("Full Size Profile Photo");//New Jframe to display pic in full size
        fullSizeFrame.setSize(profileImage.getWidth(), profileImage.getHeight());// Set frame size = image size 
        JLabel imageLabel = new JLabel(new ImageIcon(profileImage));//JLabel to display the image       
        fullSizeFrame.add(imageLabel);// Add image label to frame
        fullSizeFrame.setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "No profile photo available.");
    }
    }//GEN-LAST:event_viewProfilePhotoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileManagementPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileManagementPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bioJLabel;
    private javax.swing.JButton changeBioButton;
    private javax.swing.JButton changeCoverPhotoButton;
    private javax.swing.JButton changeProfilePhotoButton;
    private javax.swing.JPanel coverPhotoJPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel profilePhotoJPanel;
    private javax.swing.JButton updatePasswordButton;
    private javax.swing.JButton viewCoverPhotoButton;
    private javax.swing.JButton viewProfilePhotoButton;
    // End of variables declaration//GEN-END:variables
}
